import { PerspectiveCamera,Quaternion,Vector3 } from 'three';
import { flight } from '../runtime';
import { useGame } from '../../stores/game';
import { surface,touchSurface } from './state';
import { EYE_HEIGHT,SHIP_HEIGHT,groundPoint,landingSite,radial,radiusAt,resolvePlanet,safeGround,surfaceRotation,terrainNormal } from './ground';
import type { Planet } from '../universe';
import { telemetry } from '../telemetry';
const y=new Vector3(0,1,0),x=new Vector3(1,0,0),q=new Quaternion();
export function updateLandingStatus(p?:Planet){if(!p){surface.landingAvailable=false;return;}const altitude=flight.position.distanceTo(new Vector3(...p.position))-p.radius;surface.landingAvailable=p.type!=='Gas giant'&&altitude<p.radius*2;surface.landingMessage=p.type==='Gas giant'?'No solid surface':surface.landingAvailable?'L · deploy gear & landing assist':'Approach within two planetary radii';}
export function beginLanding(p?:Planet){if(!p||!surface.landingAvailable)return useGame.getState().notify(surface.landingMessage);const target=landingSite(p,flight.position);if(!target)return useGame.getState().notify('UNSAFE LANDING AREA · no dry, level terrain nearby');surface.planet=p;surface.data.planetId=p.id;surface.landingTarget.copy(target);surface.landingStart.copy(flight.position);surface.landingTime=0;surface.data.mode='landing';surface.landingRotation.copy(surfaceRotation(radial(p,target)));flight.velocity.set(0,0,0);flight.scan=0;touchSurface();useGame.getState().notify('LANDING ASSIST · dry terrain verified · gear deployed');}
export function exitOrBoard(){const d=surface.data,p=surface.planet;if(!p)return;if(d.mode==='landed'){const ship=new Vector3(...d.shipPosition),n=radial(p,ship);const side=new Vector3(1,0,0).applyQuaternion(new Quaternion(...d.shipRotation));const candidate=radial(p,ship.addScaledVector(side,3.4));if(!safeGround(p,candidate))return useGame.getState().notify('Exit obstructed by terrain. Reposition the ship.');flight.position.copy(groundPoint(p,candidate,EYE_HEIGHT));flight.rotation.copy(surfaceRotation(candidate));flight.velocity.set(0,0,0);d.mode='foot';surface.vertical=0;touchSurface();useGame.getState().notify('SURFACE EXPLORATION · WASD move · E board · Space jump');useGame.getState().save();}else if(d.mode==='foot'&&flight.position.distanceTo(new Vector3(...d.shipPosition))<6){flight.position.fromArray(d.shipPosition);flight.rotation.fromArray(d.shipRotation);flight.velocity.set(0,0,0);d.mode='landed';surface.building=false;surface.scan=0;surface.mining=0;touchSurface();useGame.getState().notify('COCKPIT ONLINE · L to launch');useGame.getState().save();}}
export function takeOff(){if(surface.data.mode!=='landed'||!surface.planet)return;const n=radial(surface.planet,flight.position);flight.position.addScaledVector(n,6);flight.rotation.copy(surfaceRotation(n)).multiply(q.setFromAxisAngle(x,.25));flight.velocity.copy(n).multiplyScalar(6);surface.data.mode='flight';surface.data.planetId=null;surface.patchRadius=0;touchSurface();useGame.getState().notify('LAUNCH COMPLETE · engines online');useGame.getState().save();}
export function updateTraversal(dt:number,camera:PerspectiveCamera,active:boolean){const d=surface.data;const p=surface.planet||(d.planetId?resolvePlanet(useGame.getState().seed,d.planetId):null);if(!p)return;surface.planet=p;const n=radial(p,flight.position);
 if(active&&d.mode==='landing'){surface.landingTime+=dt;const t=Math.min(1,surface.landingTime/8),ease=t*t*(3-2*t);const start=radial(p,surface.landingStart),end=radial(p,surface.landingTarget),dir=start.lerp(end,ease).normalize();const startR=surface.landingStart.distanceTo(new Vector3(...p.position)),targetR=radiusAt(p,dir)+SHIP_HEIGHT;flight.position.set(...p.position).addScaledVector(dir,targetR+(Math.max(0,startR-targetR))*(1-ease));flight.rotation.slerp(surface.landingRotation,1-Math.exp(-dt*2));surface.throttle=.18*(1-t);if(t===1){flight.position.copy(surface.landingTarget);d.shipPosition=flight.position.toArray();d.shipRotation=flight.rotation.toArray() as [number,number,number,number];d.mode='landed';surface.throttle=0;touchSurface();useGame.getState().notify('TOUCHDOWN · engine standby · E to exit');useGame.getState().save();}}
 if(active&&d.mode==='foot'){
 const k=flight.keys,s=useGame.getState().settings;flight.rotation.premultiply(q.setFromAxisAngle(n,-flight.mouse.x*.0015*s.sensitivity+(Number(k.has('ArrowLeft'))-Number(k.has('ArrowRight')))*dt));
 const pitch=-flight.mouse.y*.0015*s.sensitivity*(s.invertY?-1:1)+(Number(k.has('ArrowUp'))-Number(k.has('ArrowDown')))*dt;
 const trial=flight.rotation.clone().multiply(q.setFromAxisAngle(x,pitch));if(Math.abs(new Vector3(0,0,-1).applyQuaternion(trial).dot(n))<.96)flight.rotation.copy(trial);
 const forward=new Vector3(0,0,-1).applyQuaternion(flight.rotation);forward.addScaledVector(n,-forward.dot(n)).normalize();const right=forward.clone().cross(n).normalize();const movement=forward.multiplyScalar(Number(k.has('KeyW'))-Number(k.has('KeyS'))).addScaledVector(right,Number(k.has('KeyD'))-Number(k.has('KeyA')));const speed=k.has('ShiftLeft')?.9:.48;if(movement.lengthSq())movement.normalize().multiplyScalar(speed);flight.velocity.lerp(movement,1-Math.exp(-dt*9));
 const previous=flight.position.clone(),height=flight.position.distanceTo(new Vector3(...p.position))-radiusAt(p,n);const gravity=Math.max(.45,Math.min(1.6,p.radius/650));
 if(!k.has('Space'))surface.jumpReleased=true;
 if(k.has('Space')&&surface.grounded&&surface.jumpReleased){surface.vertical=.8;surface.grounded=false;surface.jumpReleased=false;surface.jetDelay=1;}
 else if(k.has('Space')&&!surface.grounded&&d.jetpack>0){surface.vertical=Math.min(1.4,surface.vertical+dt*2);d.jetpack=Math.max(0,d.jetpack-dt*18);surface.jetDelay=1.4;}
 surface.vertical-=gravity*dt;surface.jetDelay=Math.max(0,surface.jetDelay-dt);if(!surface.jetDelay)d.jetpack=Math.min(100,d.jetpack+dt*14);
 flight.position.addScaledVector(flight.velocity,dt).addScaledVector(n,surface.vertical*dt);const nextN=radial(p,flight.position);const water=(p.type==='Ocean'||p.type==='Lush')&&radiusAt(p,nextN)<=p.radius+.5;const steep=terrainNormal(p,nextN).dot(nextN)<.65;if((water||steep)&&height<EYE_HEIGHT+.4){flight.position.copy(previous);flight.velocity.set(0,0,0);}const actualN=radial(p,flight.position),floor=radiusAt(p,actualN)+EYE_HEIGHT,dist=flight.position.distanceTo(new Vector3(...p.position));if(dist<=floor){flight.position.copy(groundPoint(p,actualN,EYE_HEIGHT));surface.vertical=0;surface.grounded=true;}else surface.grounded=false;
 flight.rotation.premultiply(q.setFromUnitVectors(n,actualN));
 }
 flight.mouse.x=flight.mouse.y=0;if(!active)flight.keys.clear();
 const foot=d.mode==='foot';camera.quaternion.slerp(flight.rotation,1-Math.exp(-dt*12));camera.position.copy(foot?new Vector3():new Vector3(0,2,9).applyQuaternion(flight.rotation));camera.near=foot?.025:.1;camera.fov+=(useGame.getState().settings.fov-camera.fov)*(1-Math.exp(-dt*4));camera.updateProjectionMatrix();
 telemetry.altitude=Math.max(0,flight.position.distanceTo(new Vector3(...p.position))-radiusAt(p,radial(p,flight.position)));telemetry.atmosphere=true;telemetry.speed=flight.velocity.length();telemetry.target=null;
 if(active){d.elapsed+=dt;flight.time+=dt;if(flight.time>10){flight.time=0;useGame.getState().save();}}
}
